import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProviders from "./providers/GlobalStyleProviders";
import ContextProvider from "./providers/ContextProvider";
// import { inter } from './path/to/fonts';
import { auth, clerkMiddleware} from '@clerk/nextjs/server'
import { ClerkProvider,useAuth } from "@clerk/nextjs";
import GlobalStyleProvider from "./providers/GlobalStyleProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { userId } = await auth(); 

  return (

    <ClerkProvider>
    <html lang="en">

      <head>
      <link rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" 
      integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" 
      crossOrigin="anonymous" 
      referrerPolicy="no-referrer" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ContextProvider>
        <GlobalStyleProvider>
        {userId && <Sidebar />}
        <div className="w-full">{children}</div>
        </GlobalStyleProvider>
        </ContextProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
